name: neuropulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  # أيقونات Cupertino
  cupertino_icons: ^1.0.8


  flutter_svg: ^2.0.7  # 👈 أضف دي

  # لو ناوية تستخدم API بعدين
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # الصور الخاصة بالمشروع
  assets:
    - assets/images/logo.png
    - assets/images/spo2.png
    - assets/images/heart.png
    - assets/images/home.svg
    - assets/images/bot.svg
    - assets/images/profile.svg
    - assets/images/setting.svg
    - assets/images/alert.svg
  # لو عندك فونتات مخصصة
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: TrajanPro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700