name: neuropulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  provider: ^6.1.2
  http: ^1.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/spo2.png
    - assets/images/heart.png
    - assets/images/home.svg
    - assets/images/bot.svg
    - assets/images/profile.svg
    - assets/images/setting.svg
    - assets/images/alert.svg
    - assets/images/insight.png
    - assets/images/last.svg
    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/active.png
    - assets/images/total pa.png
    - assets/images/risk.png
    - assets/images/age.png
    - assets/images/height.png
    - assets/images/weight.svg
    - assets/images/smoking.svg
    - assets/images/man.png
    - assets/images/Disease.png
    - assets/images/patient.svg
    - assets/images/chat.svg